version: '3.7'

services:

  client-sit:
    # container_name: video-party-client
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment: 
      - REACT_APP_SERVER_TYPE="SIT"
      - REACT_APP_SERVER_PORT="9002"
      - REACT_APP_CLIENT_PORT="8002"
    image: varungujarathi9/video-party-client:sit
    ports:
      - 8002:3000

  client-uat:
    # container_name: video-party-client
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment: 
      - REACT_APP_SERVER_TYPE="UAT"
      - REACT_APP_SERVER_PORT="9001"
      - REACT_APP_CLIENT_PORT="8001"
    image: varungujarathi9/video-party-client:uat
    ports:
      - 8001:80

  client-prod:
    # container_name: video-party-client
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment: 
      - REACT_APP_SERVER_TYPE="Prod"
      - REACT_APP_SERVER_PORT="1793"
      - REACT_APP_CLIENT_PORT="80"
    image: varungujarathi9/video-party-client:latest
    ports:
      - 80:80    