version: '3.7'

services:

  client-sit:
    # container_name: video-party-client
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: varungujarathi9/video-party-client:sit
    ports:
      - 8002:3000

  client-uat:
    # container_name: video-party-client
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: varungujarathi9/video-party-client:uat
    ports:
      - 8001:80

  client-prod:
    # container_name: video-party-client
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: varungujarathi9/video-party-client:latest
    ports:
      - 80:80    