name: Docker Image CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag varungujarathi9/video-party-client:sit
    - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: varungujarathi9/video-party-client:sit
          tag_with_ref: true  
